### PR TITLE
TT-2 TT-30 UI components for chat screen, message and media messages

### PR DESCRIPTION
**Pull request by sghosalkar**

### CODE REVIEW

**Comment by sghosalkar** [comment]
Looks something like this

image

image

**Comment by galen94** [comment]
It looks great! I was curious about why the sentOn attribute is a number instead of a Date in message-service? Is that just temporary?

**Review by galen94 — APPROVED** [review]

**Comment by sghosalkar** [comment]
> It looks great! I was curious about why the sentOn attribute is a number instead of a Date in message-service? Is that just temporary?

Yes it was temporary. I was dealing with dummy data and hence had kept `sentOn` as `number` to test sorting. I've updated the PR to use backend API to fetch real data, so `sentOn` is now a `Date` string

**Review by sanatdeshpande1 — APPROVED** [review]
Looks good!

**Pull request merged**
